# Generated by Django 5.2.4 on 2025-07-09 08:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(validators=[app.models.validate_age])),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
